name: prueba2_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies: 
  flutter:  
    sdk: flutter  
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^14.2.7
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  provider: ^6.1.2
  firebase_ui_auth: ^1.14.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
