// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsF7dD7fcnMYJptizpK0ma9_bPFOLSpGw',
    appId: '1:993758453048:web:8339a827f9cf54498d75cd',
    messagingSenderId: '993758453048',
    projectId: 'prueba2-flutter-ccb4d',
    authDomain: 'prueba2-flutter-ccb4d.firebaseapp.com',
    storageBucket: 'prueba2-flutter-ccb4d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKu9YFDlvVMsh83N1ml9eT5FacRRpkQXg',
    appId: '1:993758453048:android:b95c0fa77b40284e8d75cd',
    messagingSenderId: '993758453048',
    projectId: 'prueba2-flutter-ccb4d',
    storageBucket: 'prueba2-flutter-ccb4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtnP5nmzhAOYTmvH_wlgG9FhIFm1hYeAo',
    appId: '1:993758453048:ios:7bdd48709af059398d75cd',
    messagingSenderId: '993758453048',
    projectId: 'prueba2-flutter-ccb4d',
    storageBucket: 'prueba2-flutter-ccb4d.firebasestorage.app',
    iosBundleId: 'com.example.prueba2Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtnP5nmzhAOYTmvH_wlgG9FhIFm1hYeAo',
    appId: '1:993758453048:ios:7bdd48709af059398d75cd',
    messagingSenderId: '993758453048',
    projectId: 'prueba2-flutter-ccb4d',
    storageBucket: 'prueba2-flutter-ccb4d.firebasestorage.app',
    iosBundleId: 'com.example.prueba2Flutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsF7dD7fcnMYJptizpK0ma9_bPFOLSpGw',
    appId: '1:993758453048:web:a59bc80159069ef08d75cd',
    messagingSenderId: '993758453048',
    projectId: 'prueba2-flutter-ccb4d',
    authDomain: 'prueba2-flutter-ccb4d.firebaseapp.com',
    storageBucket: 'prueba2-flutter-ccb4d.firebasestorage.app',
  );
}
